version: '2'
services:
    mooc-cloud-zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411
        environment:
            - RABBIT_ADDRESSES=docker_mooc-cloud-rabbitmq_1:5672
        restart: always